name: Print Benchmarking

on: 
  pull_request:
    types: [opened, synchronize]

jobs:
  benchmark_branch: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -e .
      - name: benchmark
        id: bench
        shell: bash
        run: |
          bench=$(python -m tests.benchmarking)
          echo "::set-output name=bench::$bench"
      - name: Auto Comment
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: >
            Benchmarking Results With Changes

            ${{steps.bench.outputs.bench}}

          pullRequestSynchronize: > 
            Benchmarking Results With Changes [Update]

            ${{steps.bench.outputs.bench}}
